project:
  type: website
  output-dir: docs

website:
  title: "Stock Synthesis (SS3) Documentation"
  navbar:
    left:
      - href: qmds/index.qmd
        text: Home
      - href: qmds/about.qmd
      - href: qmds/html.qmd
      - href: qmds/manuals.qmd
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
