project:
  type: website
  output-dir: docs

website:
  title: "Stock Synthesis (SS3) Documentation"
  navbar:
    left:
      - href: qmds/index.qmd
        text: Home
      - href: qmds/about.qmd
      - href: qmds/html.qmd
      - href: SS330_User_Manual_release.html
        text: HTML
      - href: https://github.com/e-gugliotti-NOAA/quarto-doc-website/blob/main/SS330_User_Manual_release.html
        text: full url
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
