project:
  type: website

website:
  title: "Stock Synthesis (SS3) Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: docs/about.qmd
        text: About
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto
