project:
  type: website
  output-dir: docs

website:
  title: "Stock Synthesis (SS3) Documentation"
  navbar:
    left:
      - href: qmds/index.qmd
        text: Home
      - href: qmds/about.qmd
        text: About
      - href: docs/html/SS330_User_Manual_release.html
        text: HTML
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
