project:
  type: website
  output-dir: docs

website:
  title: "Stock Synthesis (SS3)"
  # issue-url: "https://github.com/nmfs-ost/ss3-source-code/issues/new/choose"
  # repo-actions: [issue]
  navbar:
    search: false
    left:
      # - text: "Home"
      #   href: index.qmd
      #   icon: house
      - text: "SS3 User Manuals"
        icon: journal-code
        aria-label: User Manual
        menu:
          - href: https://nmfs-ost.github.io/ss3-doc/SS330_User_Manual_release.html
            text: "HTML Version"
            target: "_blank"
          - href: https://github.com/nmfs-ost/ss3-source-code/releases/latest/download/SS330_User_Manual.pdf
            text: "PDF Version (downloads on click)"
          - href: qmds/user_manual.qmd
            text: "Citing the SS3 User Manual"
      - text: "Tutorials for Getting Started"
        icon: terminal
        aria-label: Tutorials
        menu:
          - qmds/getting_started_ss3.qmd
          - qmds/ss3_model_tips.qmd
          - qmds/ss3_setup_decisions.qmd
      - text: "Vignettes for Model Features"
        icon: person-workspace
        aria-label: Vignette Workspace
        menu:
          - qmds/start_year_considerations.qmd
          - qmds/predator.qmd
          - qmds/settlement_timing.qmd
          - qmds/phases.qmd
          
    right:
       - icon: github
         aria-label: Quarto GitHub
         menu:
           - href: https://github.com/nmfs-ost/ss3-source-code
             text: "Stock Synthesis Source Code"
           - href: https://github.com/nmfs-ost/ss3-source-code/issues/new/choose
             text: "Stock Synthesis Report an Issue"
           - href: https://github.com/nmfs-ost/ss3-doc
             text: "User Manual Source Code"
           - href: https://github.com/nmfs-ost/ss3-doc/issues/new
             text: "User Manual Report an Issue"
       
format:
  html:
    link-external-newwindow: true
    theme: [sandstone, custom.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto
