project:
  type: website
  output-dir: docs

website:
  title: "Stock Synthesis (SS3) Documentation"
  # issue-url: "https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/new/choose"
  # repo-actions: [issue]
  navbar:
    left:
      - text: "Home"
        href: index.qmd
        icon: "house"
      - text: "SS3 User Manuals"
        icon: "journal-code"
        menu:
          - href: qmds/user_manual.qmd
            text: "Citing the SS3 User Manual"
          - href: https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual_release.html
            text: "HTML Version"
          - href: https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/download/v3.30.21/SS330_User_Manual.pdf
            text: "PDF Version (downloads on click)"
      - text: "Tutorials"
        icon: "person-vcard"
        menu:
          - qmds/getting_started_ss.qmd
          - qmds/ss_model_tips.qmd
    right:
       - icon: github
         menu:
           - href: https://github.com/nmfs-stock-synthesis/stock-synthesis
             text: "Stock Synthesis Source Code"
             icon: "code"
           - href: https://github.com/nmfs-stock-synthesis/stock-synthesis/issues/new/choose
             text: "Stock Synthesis Report an Issue"
             icon: "exclamation-circle"
           - href: https://github.com/nmfs-stock-synthesis/doc
             text: "User Manual Source Code"
             icon: "code"
           - href: https://github.com/nmfs-stock-synthesis/doc/issues/new
             text: "User Manual Report an Issue"
             icon: "exclamation-circle"
       
        

format:
  html:
    theme: cosmo
    toc: true
