project:
  type: website
  output-dir: docs

website:
  title: "Stock Synthesis (SS3) Documentation"
  navbar:
    left:
      - href: qmds/index.qmd
        text: "Home"
      - text: "Tutorials"
        menu:
          - about.qmd
          - tutorial.qmd
      - text: "User Manuals"
        menu:
          - href: https://nmfs-stock-synthesis.github.io/doc/SS330_User_Manual_release.html
            text: "HTML Version"
          - href: https://github.com/nmfs-stock-synthesis/stock-synthesis/releases/download/v3.30.21/SS330_User_Manual.pdf
            text: "PDF Version"
        

format:
  html:
    theme: cosmo
    toc: true
